### ISSUE TITLE
Ask the operation failed

### ISSUE THREAD

**Issue by kuaifan** [SebDanielsson/docker-wireguard-server#1]
Hello, first of all thank you for providing the mirror, I use your mirror to run and prompt the following error, please tell me how to change?

Run docker image prompt：
```
Attaching to wireguard-server
wireguard-server | [#] ip link add server type wireguard
wireguard-server | RTNETLINK answers: Not supported
wireguard-server | Unable to access interface: Protocol not supported
wireguard-server | [#] ip link delete dev server
wireguard-server | Cannot find device "server"
```

`server.conf` ：
```
[Interface]
PrivateKey = MCFApJu4oBxJwcxbuDbd7DwMGXXcZiEdSMbMa5a2wkM=
Address = 10.10.0.1/24
ListenPort = 51820
DNS = 8.8.8.8
MTU = 1420
[Peer]
PublicKey = RYFpxoBtHH6HS9DqZpMas05B0qAJMw5xfg5xTmLHakA=
AllowedIPs = 10.10.0.2/32
[Peer]
PublicKey = veG56eWjYTiESaJhmLCxRB11eVsR3twU2z4kO0nCxEs=
AllowedIPs = 10.10.0.3/32
```

**Comment by SebDanielsson** [comment]
May I see your docker-compose file or docker run command? I suspect you get this error message due to the missing --privileged flag when starting the container.

**Comment by kuaifan** [comment]
> May I see your docker-compose file or docker run command? I suspect you get this error message due to the missing --privileged flag when starting the container.

I use `docker-compose` to run, and my `docker-compose.yml` file is as follows, which has been privileged
```
version: '3.7'

services:
  wireguard-server:
    container_name: wireguard-server
    image: sebdanielsson/wireguard-server
    privileged: true
    sysctls:
      - 'net.ipv4.ip_forward=1'
    ports:
      - '51820:51820/udp'
    volumes:
      - './etc/server.conf:/etc/wireguard/server.conf'
```
